// Code generated by protoc-gen-gogo.
// source: dropsonde_status.proto
// DO NOT EDIT!

package events

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type DropsondeStatus struct {
	SentCount        *uint64 `protobuf:"varint,1,req,name=sentCount" json:"sentCount,omitempty"`
	ErrorCount       *uint64 `protobuf:"varint,2,req,name=errorCount" json:"errorCount,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DropsondeStatus) Reset()         { *m = DropsondeStatus{} }
func (m *DropsondeStatus) String() string { return proto.CompactTextString(m) }
func (*DropsondeStatus) ProtoMessage()    {}

func (m *DropsondeStatus) GetSentCount() uint64 {
	if m != nil && m.SentCount != nil {
		return *m.SentCount
	}
	return 0
}

func (m *DropsondeStatus) GetErrorCount() uint64 {
	if m != nil && m.ErrorCount != nil {
		return *m.ErrorCount
	}
	return 0
}

func init() {
}
